@startuml Main Flow Game Sequence Diagram

title Main flow of the game 

actor User
participant Director
participant Level
participant Game
participant HUD
participant GameOver

activate Director
Director -> Level: new(current_level)
activate Level
Level -> Game : new()
activate Game
Game -> HUD : initialize(tile_size, font_size)
activate HUD
HUD --> Game : renders
deactivate HUD

alt Player loses all lives
    Game -> Director : push_scene(GameOver)
    Director -> GameOver : new()
    activate GameOver
    User -> GameOver : Press "Enter"
    GameOver -> Director : change_scene(first_level)
    deactivate GameOver
    Director -> Level : stack.append(Level)
end

alt Player completes level
    Level -> Director : go_to_next_level()
    Director -> Level : new(next_level)
end

alt Player restarts level
    Game -> Director : pop_scene()
    Game -> Director : change_scene(new_scene)
    Director -> Level : new(current_level)
end

@enduml