@startuml Pause System Sequence Diagram

title Pause System 

actor User
participant Director 
participant Level 
participant PauseMenu as "Pause Menu"
participant ResourceManager as "Resource Manager"

activate Director
activate Level
User -> Level : Press "P"
Level -> Director : push_scene(PauseMenu)
deactivate Level
Director -> PauseMenu : new()
activate PauseMenu
PauseMenu -> ResourceManager : load_font()
activate ResourceManager
PauseMenu <-- ResourceManager : Font
deactivate ResourceManager
PauseMenu -> PauseMenu : draw()

alt [Press continue]
    PauseMenu -> Director : pop_scene()
    deactivate PauseMenu
    Director -> Level : stack.pop()
    activate Level
    deactivate Level
    
else [Press restart]
    activate PauseMenu
    PauseMenu -> Director : change_scene(first_level)
    deactivate PauseMenu
    Director -> Level : new()
    activate Level
end

deactivate Level
deactivate Director
