@startuml Game Initialization

title Game Initialization

actor User
participant "Main"
participant "Director"
participant "Main Menu"
participant "Game"

User -> Main: Executes the program
Main -> Director: new()
activate Director
Main -> Director: stack_scene(MainMenu)
Director -> MainMenu: new()
Main -> Director: run()
Director -> MainMenu: loop()
MainMenu --> Director: Wait for event
User -> MainMenu: Press "Play"
MainMenu -> Director: stack_scene(Game)
Director -> Game: new()
activate Game
Game -> Game: _load_level()
deactivate Game
deactivate Director

@enduml