@startuml Settings Menu Sequence Diagram

title Settings Menu

actor User
participant Main
participant Director
participant MainMenu
participant Game

User -> Main: Executes the program
Main -> Director: new()
activate Director
Main -> Director: stack_scene(MainMenu)
Director -> MainMenu: new()
Main -> Director: run()
Director -> MainMenu: loop()
MainMenu --> Director: Wait for event
User -> MainMenu: Press "Settings"

@enduml