@startuml Settings Menu Sequence Diagram

title Settings Menu

actor User
participant Main
participant Director
participant MainMenu as "Main Menu"
participant SettingsMenu as "Settings Menu"

User -> Main: Executes the program
Main -> Director: new()
activate Director
Main -> Director: push_scene(MainMenu)
Director -> MainMenu: new()
activate MainMenu
Main -> Director: run()
Director -> MainMenu: loop()
MainMenu --> Director: Wait for event
User -> MainMenu: Press "Settings"
MainMenu -> Director: push_scene(SettingsMenu)
Director -> SettingsMenu: new()
activate SettingsMenu
SettingsMenu --> Director: Wait for event
User -> SettingsMenu: Press "Return"
SettingsMenu -> Director: pop_scene()
deactivate SettingsMenu
Director -> MainMenu: stack.pop()

@enduml