@startuml Class Diagram Sprite

title general class diagram (II)

class Level {
    + update(delta_time)
    + go_to_next_level()
}

class Sprite {
    
}

abstract class Berry {
    + update(player) {abstract}
}

class CoinBerry {
    
}

class EnergyBerry {
    
}

class HealthBerry {
    
}

class RageBerry {
    
}

abstract class Projectile {
    - _move(delta_time) {abstract}
    - _deactive_projectile() {abstract}
}

class Spore {
    
}

class Acorn{
    
}

abstract class ProjectilesPool {
    - _create_pool() {abstract}
    + shoot(pos_x, pos_y, direction) {abstract}
}

class AcornPool {
    
}

class SporePool {
    
}

abstract class Character {
    + update(delta_time) {abstract}
}

class Player {
    
}

abstract class Enemy {
    - _defeat()
    - _deal_damage_to_player()
}

abstract class MovingEnemy {
    - _move(delta_time)
}

class Hedgehog {
    
}

class Fox {
    
}

class Bat {
    
}

class Bear {
    
}

abstract class Shooter {
    - _shoot() {abstract}
}

class Squirrel {
    
}

class Mushroom {
    
}

enum MushroomDirection {
    
}

enum MushroomState {
    
}

Level --> Sprite

Sprite <|-- Berry
Sprite <|-- Character
Sprite <|-- Projectile

Berry <|-- CoinBerry
Berry <|-- EnergyBerry
Berry <|-- HealthBerry
Berry <|-- RageBerry


ProjectilesPool <|-- SporePool
ProjectilesPool <|-- AcornPool


Projectile <|-- Spore
Projectile <|-- Acorn

SporePool o-- Spore
AcornPool o-- Acorn

Character <|-- Player
Character <|-- Enemy

Enemy <|-- MovingEnemy
Enemy <|-- Shooter

MovingEnemy <|-- Hedgehog
MovingEnemy <|-- Fox
MovingEnemy <|-- Bat
MovingEnemy <|-- Bear

Shooter <|-- Squirrel
Shooter <|-- Mushroom
Shooter --> ProjectilesPool
Squirrel --> AcornPool
Mushroom --> MushroomDirection
Mushroom --> MushroomState
Mushroom --> SporePool

@enduml